### ISSUE TITLE
Nulldereference if rift activity text is trying to render with rifts disabled

### ISSUE THREAD

**Issue by FalcoGer** [Gravydigger/statushud#1]
When trying to add riftactivity and rifts are disabled in the world, vintage story crashes.

```text
Exception: Object reference not set to an instance of an object.
at StatusHud.StatusHudText.Set(String value) in D:\Git Repositories\statushud\statushud\text.cs:line 191
at StatusHud.StatusHudRiftAvtivityRenderer.setText(String value) in D:\Git Repositories\statushud\statushud\elements\riftactivity.cs:line 149
at StatusHud.StatusHudRiftActivityElement..ctor(StatusHudSystem system, Int32 slot, StatusHudTextConfig config) in D:\Git Repositories\statushud\statushud\elements\riftactivity.cs:line 44
at StatusHud.StatusHudSystem.instantiate(Int32 slot, String name) in D:\Git Repositories\statushud\statushud\system.cs:line 107
at StatusHud.StatusHudSystem.Set(Int32 slot, String name) in D:\Git Repositories\statushud\statushud\system.cs:line 285
at StatusHud.StatusHudConfigManager.LoadElements(StatusHudSystem system) in D:\Git Repositories\statushud\statushud\config.cs:line 115
at StatusHud.StatusHudSystem.StartClientSide(ICoreClientAPI capi) in D:\Git Repositories\statushud\statushud\system.cs:line 156
at Vintagestory.Common.ModLoader.TryRunModPhase(Mod mod, ModSystem system, ICoreAPI api, ModRunPhase phase) in VintagestoryLib\Common\API\ModLoader.cs:line 660
```

**Comment by Gravydigger** [comment]
Fixed as of https://github.com/Gravydigger/statushud/commit/5827b9747f9bffe7c17c82d8279eaebbc67e2619.
